<?php

return [
    'max_links' => 7,
    'platforms' => [
        'website' => [
            'label' => 'Website',
            'icon' => 'bi-globe2',
            'class' => 'social-website',
            'prefix' => '',
            'placeholder' => 'https://example.com',
        ],
        'facebook' => [
            'label' => 'Facebook',
            'icon' => 'bi-facebook',
            'class' => 'social-facebook',
            'prefix' => 'https://facebook.com/',
            'placeholder' => 'username',
        ],
        'x' => [
            'label' => 'X',
            'icon' => 'bi-twitter-x',
            'class' => 'social-x',
            'prefix' => 'https://x.com/',
            'placeholder' => 'username',
        ],
        'instagram' => [
            'label' => 'Instagram',
            'icon' => 'bi-instagram',
            'class' => 'social-instagram',
            'prefix' => 'https://instagram.com/',
            'placeholder' => 'username',
        ],
        'youtube' => [
            'label' => 'YouTube',
            'icon' => 'bi-youtube',
            'class' => 'social-youtube',
            'prefix' => 'https://youtube.com/@',
            'placeholder' => 'channel',
        ],
        'tiktok' => [
            'label' => 'TikTok',
            'icon' => 'bi-tiktok',
            'class' => 'social-tiktok',
            'prefix' => 'https://tiktok.com/@',
            'placeholder' => 'username',
        ],
        'linkedin' => [
            'label' => 'LinkedIn',
            'icon' => 'bi-linkedin',
            'class' => 'social-linkedin',
            'prefix' => 'https://linkedin.com/in/',
            'placeholder' => 'username',
        ],
        'pinterest' => [
            'label' => 'Pinterest',
            'icon' => 'bi-pinterest',
            'class' => 'social-pinterest',
            'prefix' => 'https://pinterest.com/',
            'placeholder' => 'username',
        ],
        'telegram' => [
            'label' => 'Telegram',
            'icon' => 'bi-telegram',
            'class' => 'social-telegram',
            'prefix' => 'https://t.me/',
            'placeholder' => 'username',
        ],
        'whatsapp' => [
            'label' => 'WhatsApp',
            'icon' => 'bi-whatsapp',
            'class' => 'social-whatsapp',
            'prefix' => 'https://wa.me/',
            'placeholder' => '15551234567',
        ],
        'github' => [
            'label' => 'GitHub',
            'icon' => 'bi-github',
            'class' => 'social-github',
            'prefix' => 'https://github.com/',
            'placeholder' => 'username',
        ],
        'discord' => [
            'label' => 'Discord',
            'icon' => 'bi-discord',
            'class' => 'social-discord',
            'prefix' => 'https://discord.gg/',
            'placeholder' => 'invite',
        ],
        'behance' => [
            'label' => 'Behance',
            'icon' => 'bi-behance',
            'class' => 'social-behance',
            'prefix' => 'https://behance.net/',
            'placeholder' => 'username',
        ],
        'dribbble' => [
            'label' => 'Dribbble',
            'icon' => 'bi-dribbble',
            'class' => 'social-dribbble',
            'prefix' => 'https://dribbble.com/',
            'placeholder' => 'username',
        ],
        'twitch' => [
            'label' => 'Twitch',
            'icon' => 'bi-twitch',
            'class' => 'social-twitch',
            'prefix' => 'https://twitch.tv/',
            'placeholder' => 'username',
        ],
        'spotify' => [
            'label' => 'Spotify',
            'icon' => 'bi-spotify',
            'class' => 'social-spotify',
            'prefix' => 'https://open.spotify.com/',
            'placeholder' => 'profile link',
        ],
        'threads' => [
            'label' => 'Threads',
            'icon' => 'bi-threads',
            'class' => 'social-threads',
            'prefix' => 'https://threads.net/@',
            'placeholder' => 'username',
        ],
        'reddit' => [
            'label' => 'Reddit',
            'icon' => 'bi-reddit',
            'class' => 'social-reddit',
            'prefix' => 'https://reddit.com/',
            'placeholder' => 'u/username',
        ],
    ],
];
